### ISSUE TITLE
关于字体问题

### ISSUE THREAD

**Issue by DREAMSKYWORLD** [CTeX-org/lshort-zh-cn#10]
在 2.3.6（12页）特殊西文符号与重音一节
英文原版为
```latex
H\^otel, na\"\i ve, \'el\`eve,\\
sm\o rrebr\o d, !`Se\~norita!,\\
Sch\"onbrunner Schlo\ss{}
Stra\ss e
```
而中文是
```latex
H\^otel, na\"\i ve, \’el\‘eve,\\
sm\o rrebr\o d, !‘Se\ norita!,\\
Sch\"onbrunner Schlo\ss{}
Stra\ss e
```
其中的 **`** 和 **'** 在中文显示为单引号 **‘** 和 **’** 。
[查看最新版本](https://ctan.org/pkg/lshort-zh-cn)没有改动。我用的是Linux的Document Viewer 查看pdf文件的。
我第一次发Issues,如果有错误请原谅。
原标题为 关于排版问题， 已改为 关于字体问题。

**Comment by louisstuart96** [comment]
这个是字体问题。英文版使用的字体是 OpenType 字体 Computer Modern Unicode，中文版用了 Type1 的 Latin Modern 字体。在这几个引号的形状上，Latin Modern 字体（Type1 / Unicode) 和 TeX / LaTeX 默认的 CM 字体是一致的，而 CM Unicode 和前述字体有一点区别。

**Comment by zepinglee** [comment]
`lshort-zh-cn` 作为一本入门读物不应该让新手产生困惑：这里要输入 `'`/`"` 还是 `‘’`/`“”`？

另外，应该让新手从 pdf 左边复制代码就能复现结果，不必去找 lshort 源码。

**Comment by muzimuzhi** [comment]
考虑加一个「键盘上的键 - 在本手册中的输出形式」的表格？

**Comment by Stone-Zeng** [comment]
我觉得可以加个脚注说明一下这个 symbol 对应的 glyph 有两种样子。
