### ISSUE TITLE
建议项目改名为“lshort-chinese”或“lshort-zh-cn”

### ISSUE THREAD

**Issue by zepinglee** [CTeX-org/lshort-zh-cn#13]
目前本项目在 ctan 上名称为 [lshort-zh-cn](https://ctan.org/pkg/lshort-zh-cn)，在 TeX Live 中收录的名称为 lshort-chinese，建议 GitHub 项目与之保持一致。

**Comment by louisstuart96** [comment]
@zohooo document-builder 组好像没有权限给项目改名。

**Comment by Liam0205** [comment]
@louisstuart96 要改成什么？

**Comment by louisstuart96** [comment]
@Liam0205 看issue的题目……

**Comment by Liam0205** [comment]
@louisstuart96 题目不是「或」吗？所以到底要用哪一个？

**Comment by Liam0205** [comment]
好了，我自作主张一下。

CTAN 是 `lshort-zh-cn`，TeX Live 是 `lshort-chinese`，MiKTeX 是 `lshort-zh-cn`。三比二，我选 `lshort-zh-cn`。

**Comment by Liam0205** [comment]
done.
