### ISSUE TITLE
代码库结构调整

### ISSUE THREAD

**Issue by louisstuart96** [CTeX-org/lshort-zh-cn#18]
CTAN 的人要求把 chap 一级的文件都放到 src 目录下（原文是放在 lshort-zh-cn 根目录下，没明白为啥，在交涉）。我在提交给 CTAN 的版本改动了，代码库还没动，等确定的消息吧

**Comment by stone-zeng** [comment]
现在 CTAN 上面的目录结构已和 GitHub repo 保持一致。
