### ISSUE TITLE
TeX Live 迟迟未收录 v6.01

### ISSUE THREAD

**Issue by muzimuzhi** [CTeX-org/lshort-zh-cn#20]
查 texlive svn repo 知，texlive 没有收录 Apr 18 2019 的 lshort-zh-cn v6.01（texlive 按 lshort-chinese 收录）。请问维护者是否了解具体原因？

相关链接：http://www.tug.org/svn/texlive/trunk/Master/texmf-dist/doc/latex/lshort-chinese

**Comment by stone-zeng** [comment]
现在已经可以更新到了，虽然清华源可能还要等几个小时。

**Comment by muzimuzhi** [comment]
确认已更新
http://www.tug.org/svn/texlive/trunk/Master/texmf-dist/doc/latex/lshort-chinese/
