### ISSUE TITLE
tabular 环境未介绍 align 可选参数

### ISSUE THREAD

**Issue by muzimuzhi** [CTeX-org/lshort-zh-cn#22]
目前的介绍
https://github.com/CTeX-org/lshort-zh-cn/blob/94979dcc2e98c305c99c0b84cc5ffbe46ba045a5/src/chap/chap.03.elements.tex#L507-L516

完整的用法应为
```latex
\begin{tabular}[⟨align⟩]{⟨column-spec⟩}
⟨item1⟩ & ⟨item2⟩ & … \\
\hline
⟨item1⟩ & ⟨item2⟩ & … \\
\end{tabular}
```

建议
 * 在 tabular 环境的完整语法中增加 `\oarg{align}`
 * 补充相应的文字描述
------

参考垂直盒子
https://github.com/CTeX-org/lshort-zh-cn/blob/94979dcc2e98c305c99c0b84cc5ffbe46ba045a5/src/chap/chap.03.elements.tex#L911-L917

![image](https://user-images.githubusercontent.com/6376638/62425102-cc331800-b709-11e9-8f9a-f4313c352cca.png)

**Comment by louisstuart96** [comment]
在 fe23896 里大致改了一下。
这里其实有一点倾向性，或者引导性。因为这个可选参数一般人用得少，包括第六章里 `\cite` 的可选参数，许多新手见到完整的写法肯定会不管三七二十一照抄，然后用出幺蛾子的。

**Comment by muzimuzhi** [comment]
想起来开这个 issue 的直接原因了：lshort-zh-cn 中介绍 `\parbox` 和 `minipage` 的（外部）纵向对齐可选参数时引用了 `tabular` 的可选参数，但 `tabular` 里没有介绍。
https://github.com/CTeX-org/lshort-zh-cn/blob/f9ae1e5072ba1ee6201da0ecf71106d222f94e8e/src/chap/chap.03.elements.tex#L909-L921
