### ISSUE TITLE
标准文档类纸型选项的描述有误

### ISSUE THREAD

**Issue by muzimuzhi** [CTeX-org/lshort-zh-cn#27]
当前描述
https://github.com/CTeX-org/lshort-zh-cn/blob/98efd33178bc7823a9812e6223c650b98c881af7/src/chap/chap.01.basics.tex#L228-L237

存在问题
 - 标准文档类的纸型选项（a4paper，b5paper，letterpaper，还包括 landscape），只（通过修改 `\paperwidth` 和 `\paperheight`）影响输出区域，不影响纸张大小
 - 默认纸张大小，在 texlive 2019 中已经为 a4paper，不再是 letterpaper。从[这篇文章](https://zhuanlan.zhihu.com/p/19779481)的截图看，texlive 2014 时默认纸张大小就是 a4paper 了。（下图来源：李阿玲，《[TeX Live 2019安装指南](https://zhuanlan.zhihu.com/p/64555335)》，知乎专栏）
    ![image](https://pic1.zhimg.com/80/v2-be6b4e16694de51e13b97621a7c06e08_hd.jpg)
 - 引擎默认纸张大小可通过 `tlmgr paper` 获取（和修改），例如
    ```bash
    $ tlmgr paper
    Current dvipdfmx paper size (from /usr/local/texlive/2019basic/texmf-config/dvipdfmx/dvipdfmx.cfg): a4
    Current dvips paper size (from /usr/local/texlive/2019basic/texmf-config/dvips/config/config.ps): a4
    Current pdftex paper size (from /usr/local/texlive/2019basic/texmf-config/tex/generic/config/pdftexconfig.tex): a4
    Current xdvi paper size (from /usr/local/texlive/2019basic/texmf-config/xdvi/XDvi): a4
    ```

修改建议
 - 说明只修改输出区域，不修改修改纸张大小（默认为 a4paper）
 - 对修改纸张大小的需求，建议用户使用 `geometry` 和 `typearea` 等宏包

**Comment by muzimuzhi** [comment]
上述描述有错误。我再看看

**Comment by louisstuart96** [comment]
`letterpaper`是`article`文档类的参数，另外如果如果文档类选项和实际纸张大小不一致的话，`letterpaper`控制的`\paperheight`和`\paperwidth`以及页边距等可能与纸张尺寸有冲突。
这一点不太好写，不好在一开头就交待geometry宏包。

**Comment by mybelovedlz** [comment]
texlive确实缺省大小为a4paper，但是修改文档类参数后查看PDF属性发现“页面大小”确实修改过了
