### ISSUE TITLE
分割号“/”不应出现在一行之首

### ISSUE THREAD

**Issue by sikouhjw** [CTeX-org/lshort-zh-cn#34]
代码对应
https://github.com/CTeX-org/lshort-zh-cn/blob/656ce8f247285f6b5349ec7d26bd1598b5303caf/src/chap/chap.02.text.tex#L8
编译结果
![1](https://user-images.githubusercontent.com/49770925/73053411-9efa4200-3ec2-11ea-9311-ffa6b2d6c10d.png)
个人建议解决措施
```latex
\texttt{xelatex} 和 \texttt{lualatex} 编译命令配合 \cls{ctex} 宏包~/ 文档类的方式成为当前的主流中文排版支持方式。
```
编译结果
![2](https://user-images.githubusercontent.com/49770925/73053655-3a8bb280-3ec3-11ea-9dbf-f5f8d494b4b9.png)

**Comment by sikouhjw** [comment]
参考：GB/T 15834―2011 标点符号用法，http://people.ubuntu.com/~happyaron/l10n/GB(T)15834-2011.html
> 5.1.9 分隔号占半个字位置，不出现在一行之首或一行之末。

**Comment by stone-zeng** [comment]
这个原则上应该在 `xeCJK` 的层面解决，但貌似没有比较直接的手段来处理。
