### ISSUE TITLE
建议补充 `draft` 选项的内容

### ISSUE THREAD

**Issue by sikouhjw** [CTeX-org/lshort-zh-cn#35]
在文中没有提到使用 `draft` 文档类选项时会让插入的图片只显示 `filename`

**Comment by zepinglee** [comment]
感觉这部分不太适合新手阅读

**Comment by sikouhjw** [comment]
感觉可以在 `sec 3.7 图片` 那里补充，图片那节已经讲完了路径和插入方式，再提 `draft` 不会看不懂

**Comment by louisstuart96** [comment]
3.7节整体上写得比较粗略，在下一次改动的时候可能要重写。

draft这一块儿可以写一写。很多论文模板里采取了`\setkeys{Gin}{draft=false}`这样偏底层的做法，可以考虑提一下，但不鼓励亲自这样改（`graphics`宏包文档的建议用法是用宏包选项的`final`覆盖文档类全局选项`draft`）。
