### ISSUE TITLE
不知能不能再加点内容

### ISSUE THREAD

**Issue by OsbertWang** [CTeX-org/lshort-zh-cn#36]
可否为源代码 3.1 再添加些注释。这几天已经见到有用户直接在 tex 文件中写 `\usepackage{...}` 了。
另外，3.9.2 节能再添加一个 `subcaption` 中 `subfigure` 的用法吗?

**Comment by zepinglee** [comment]
这个 issue 的标题和描述不够清晰

1. 要加什么注释？
2. 在 tex 文件中写 `\usepackage` 似乎没啥问题啊。

**Comment by stone-zeng** [comment]
> ![image](https://user-images.githubusercontent.com/18233088/75602174-c06fce80-5afd-11ea-8fef-f61a10ab7d07.png)
>
> 这个例子，能不能在 `...` 那些地方，加点注释，昨天还是前天，真的看到有人写 `\usepackage{...}`

**Comment by zepinglee** [comment]
理解错了【捂脸

**Comment by OsbertWang** [comment]
是我没在这里写清楚。我也很好奇为什么有用户真的写 `...`
