### ISSUE TITLE
\emph使用问题

### ISSUE THREAD

**Issue by mybelovedlz** [CTeX-org/lshort-zh-cn#38]
第一是不太明白为什么CTAN上和github上的lshort长得不太一样。。。。
第二是两者都用下划线而非斜体表示强调，但在文字解释部分又都说\emph命令使用斜体表强调

**Comment by stone-zeng** [comment]
1. GitHub 的这个仓库和 CTAN 上面的是同一份文档，不知道你发现的不一样指出在哪里。
2. 中文习惯上不使用斜体，因此 `ctex` 包默认将斜体映照到楷体上。实际上，本文档大多数情况下使用 `\textbf` 表示强调（**注意：这不是一个好的写法！**），几乎所有 `\emph` 都仅限于纯西文的情况。当然，不排除有些滥用 / 笔误的地方，欢迎指正。

**Comment by mybelovedlz** [comment]
比如github上的lshort114分钟而CTAN上的110分钟，当然两者在布局上另有很多不同，不一一说明。
无论是CTAN上的还是github上的`\emph`均是西文强调而非中文强调，两者亦解释为“斜体”而非“下划线”，我提出的问题主要是针对文字与代码实现效果不一致的。
![image](https://user-images.githubusercontent.com/52537886/77979916-80884b00-7338-11ea-815a-06d353c2a025.png)

**Comment by sikouhjw** [comment]
> 比如github上的lshort114分钟而CTAN上的110分钟，当然两者在布局上另有很多不同，不一一说明。

GitHub 上 114 分钟的是**未发行的**，release 才是发行到 CTAN 上的

**Comment by mybelovedlz** [comment]
> GitHub 上 114 分钟的是未发行的，release 才是发行到 CTAN 上的

我指的是CTAN网站上而非本地的texlive2019上的，当然在texlive2020发布后三者者应该是一致的。

**Comment by muzimuzhi** [comment]
@mybelovedlz 
> 第二是两者都用下划线而非斜体表示强调，但在文字解释部分又都说\emph命令使用斜体表强调

`\emph` 的语义是强调，在 LaTeX2e 的默认风格是意大利斜体。`ulem` 宏包会把它改成下划线。使用 `\usepackage[normalem]{ulem}` 可以还原到斜体。

在 lshort-zh-cn 的正文中，`\emph` 应使用斜体。最近的 `xeCJK` 更新使得它变成了下划线。已在 https://github.com/CTeX-org/lshort-zh-cn/commit/f9ae1e5072ba1ee6201da0ecf71106d222f94e8e 修复。

**Comment by stone-zeng** [comment]
> 我指的是CTAN网站上而非本地的texlive2019上的，两者的构建时间均为2020年三月，当然在texlive2020发布后三者者应该是一致的。

目前 `lshort-zh-cn` 只发布到了 v6.01，github 和 ctan 上面都没有 2020 年构建的版本。如果不是这样，可否提供具体的链接？

**Comment by mybelovedlz** [comment]
@stone-zeng 我没有意识到lshort上的时间是编译的时间而非一开始写好的，乌龙，我搞错了。
