### ISSUE TITLE
最新版 lshort-zh-cn 无法在最新版 TeXLive2019 编译通过

### ISSUE THREAD

**Issue by sikouhjw** [CTeX-org/lshort-zh-cn#39]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- TeX 发行版
  - [x] TeX Live2019
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题

指定清华源 `tlmgr option repository https://mirrors.tuna.tsinghua.edu.cn/CTAN/systems/texlive/tlnet`，升级所有宏包后，按照 `README-zh.md` 中的
```latex
xelatex lshort-zh-cn
makeindex -s lshort-zh-cn.ist lshort-zh-cn
xelatex lshort-zh-cn
xelatex lshort-zh-cn
```
步骤编译，第一步就报错了

## 最小工作示例（MWE）

不是 MWE，偷懒了 [https://github.com/CTeX-org/lshort-zh-cn](https://github.com/CTeX-org/lshort-zh-cn)

（用 XeLaTeX 编译后）输出

```latex
Undefined control sequence.
<recently read> \Bbbk 
```
找到对应的位置
https://github.com/CTeX-org/lshort-zh-cn/blob/656ce8f247285f6b5349ec7d26bd1598b5303caf/src/chap/sec.symbol.table.tex#L379
```latex
 \AMSSYM{\hbar}             & \AMSSYM{\hslash}           & \AMSSYM{\Bbbk}            \\
```
如何解决？

## 链接

- GitHub: [https://github.com/CTeX-org/lshort-zh-cn](https://github.com/CTeX-org/lshort-zh-cn)

**Comment by louisstuart96** [comment]
Windows下不能复现。为解决问题，可能需要在issue里提交.log文件（编辑issue的时候点下方的"Attach files by dragging..."可上传文件）。

**Comment by sikouhjw** [comment]
> Windows下不能复现。为解决问题，可能需要在issue里提交.log文件（编辑issue的时候点下方的"Attach files by dragging..."可上传文件）。

已上传
[lshort-zh-cn.log](https://github.com/CTeX-org/lshort-zh-cn/files/4409456/lshort-zh-cn.log)

**Comment by louisstuart96** [comment]
> 已上传

log里没有看到异常。可能得你自己写个MWE测试一下单独导入amssymb包，看看`\Bbbk`这个符号正常与否。

**Comment by sikouhjw** [comment]
> log里没有看到异常。可能得你自己写个MWE测试一下单独导入amssymb包，看看`\Bbbk`这个符号正常与否。

我检查了 `amssymb.sty`，发现是我以前把定义 `\Bbbk` 那行注释掉了...太蠢了我

**Comment by muzimuzhi** [comment]
不要直接改动 `TEXMFDIST` 目录里的文件。把增删改的文件，都放到 `TEXMFLOCAL`/`TEXMFHOME` 里去，这样能通过文件全路径看出差异，方便查错。三个 `TEXMF<XXX>` 的含义参考 https://zhuanlan.zhihu.com/p/113124407 和 [texlive 的文档](https://www.tug.org/texlive/doc.html)。

**Comment by muzimuzhi** [comment]
> 不要直接改动 `TEXMFDIST` 目录里的文件。

更一般地，为了方便排查错误，如果文件内容变了，那么文件标识也要随之更改。文件标识可以是
 - 形如 `\ProvidePackage{<pkg name>}[yyyy/mm/dd <version info>]` 中的日期、版本和说明信息。
 - 文件路径，见上条评论
