### ISSUE TITLE
能否统一目录的衬线字体与非衬线字体

### ISSUE THREAD

**Issue by chenxijun** [CTeX-org/lshort-zh-cn#40]
![image](https://user-images.githubusercontent.com/16610294/78744596-9333fd00-7994-11ea-8995-c46b25b53490.png)

**Comment by muzimuzhi** [comment]
就你截图中展示的部分，
 - 西文正文为衬线体（正常和粗体），表示宏包名的单词 `xeCJK` 使用非衬线体
 - 中文，用宋体和正常衬线体搭配、黑体和加粗衬线体搭配

整个文档一以贯之地使用了以上的样式和搭配，不确定你提出的「统一」需求具体是什么。

**Comment by chenxijun** [comment]
> 就你截图中展示的部分，
> 
> * 西文正文为衬线体（正常和粗体），表示宏包名的单词 `xeCJK` 使用非衬线体
> * 中文，用宋体和正常衬线体搭配、黑体和加粗衬线体搭配
> 
> 整个文档一以贯之地使用了以上的样式和搭配，不确定你提出的「统一」需求具体是什么。

了解了，抱歉是我不清楚文档规范导致的误解
