### ISSUE TITLE
[样式讨论] 表格题注末尾的句号是否必要？

### ISSUE THREAD

**Issue by muzimuzhi** [CTeX-org/lshort-zh-cn#43]
目前 lshort-zh-cn 中所有表格题注均以句号结尾，是否必要？

**Comment by zepinglee** [comment]
`lshort` 原文的表题末尾是带表标点符号的。这个是因为 LaTeX 的习惯是将表题和表注写到一起，所以经常是一大段，所以即便表题不是完整的句子，也会用句点结尾，比如 Nature。当然也有不用句点的，比如 The LaTeX Companion。中文的习惯是将表题和表注分开，而且表题一般是短语，所以通常末尾不用标点符号。

**Comment by stone-zeng** [comment]
图和代码的题注因为在后面，所以就不改了。

**Comment by muzimuzhi** [comment]
谢谢
