### ISSUE TITLE
关于西文字体的疑问

### ISSUE THREAD

**Issue by sikouhjw** [CTeX-org/lshort-zh-cn#47]
https://github.com/CTeX-org/lshort-zh-cn/blob/4ceb12734252926a749b4e0c84708a034e250a5c/src/lshort-zh-cn-style.sty#L30-L52
为什么都用同一种字体？这个字体有什么优点/是出于什么目的这么做的吗？单纯好奇

**Comment by stone-zeng** [comment]
这个是 [Computer Modern Unicode](https://ctan.org/pkg/cm-unicode) 字体，相当于是 Knuth 的 Computer Modern 的复刻 + 扩充。它的文件命名方式是 `cmun<style>.otf`，具体如下：

- `cmunrm.otf`: Computer Modern Unicode Serif Roman
- `cmunbi.otf`: Computer Modern Unicode Serif Bold Italic
- `cmunbl.otf`: Computer Modern Unicode Serif Bold Slanted
- `cmunbx.otf`: Computer Modern Unicode Serif Bold
- `cmunrb.otf`: Computer Modern Unicode Serif Bold Nonextended
- `cmunsl.otf`: Computer Modern Unicode Serif RomanSlanted
- `cmunti.otf`: Computer Modern Unicode Serif Italic
- `cmunci.otf`: Computer Modern Unicode Classical Serif Italic
- `cmunsi.otf`: Computer Modern Unicode Sans Serif Oblique
- `cmunso.otf`: Computer Modern Unicode Sans Serif Bold Oblique
- `cmunss.otf`: Computer Modern Unicode Sans Serif
- `cmunssdc.otf`: Computer Modern Unicode Sans Serif DemiCondensed
- `cmunsx.otf`: Computer Modern Unicode Sans Serif Bold
- `cmunit.otf`: Computer Modern Unicode Typewriter Italic
- `cmunst.otf`: Computer Modern Unicode Typewriter Oblique
- `cmuntt.otf`: Computer Modern Unicode Typewriter Regular
- `cmunvi.otf`: Computer Modern Unicode Typewriter Variable Italic
- `cmunvt.otf`: Computer Modern Unicode Typewriter Variable
- `cmunui.otf`: Computer Modern Unicode Serif Upright Italic
- `cmuntb.otf`: Computer Modern Unicode Typewriter Bold
- `cmuntx.otf`: Computer Modern Unicode Typewriter Bold Italic
- `cmunorm.otf`: Computer Modern Unicode Concrete Roman
- `cmunobx.otf`: Computer Modern Unicode Concrete Bold
- `cmunobi.otf`: Computer Modern Unicode Concrete Bold Italic
- `cmunoti.otf`: Computer Modern Unicode Concrete Italic
- `cmunbmr.otf`: Computer Modern Unicode Bright Roman
- `cmunbmo.otf`: Computer Modern Unicode Bright Oblique
- `cmunbsr.otf`: Computer Modern Unicode Bright Semibold
- `cmunbso.otf`: Computer Modern Unicode Bright Semibold Oblique
- `cmunbbx.otf`: Computer Modern Unicode Bright Bold
- `cmunbxo.otf`: Computer Modern Unicode Bright Bold Oblique
- `cmunbtl.otf`: Computer Modern Unicode Typewriter Light
- `cmunbto.otf`: Computer Modern Unicode Typewriter Light Oblique

参考：<https://cm-unicode.sourceforge.io/>
