### ISSUE TITLE
添加 filecontents 环境及相关示例进行改写

### ISSUE THREAD

**Issue by sikouhjw** [CTeX-org/lshort-zh-cn#52]
在文中增加 `filecontents` 环境的说明，感觉可以放 *sec 3.5 特殊环境* 里面，优点：
- 输入方便，不必再手动创建文件
- 方便让提问者提供 MWE

比如对
https://github.com/CTeX-org/lshort-zh-cn/blob/34a54eb40627511c411a33ae7608e648c9f1f46e/src/chap/chap.06.spec.tex#L264-L291
这部分改写，改为
```tex
\begin{filecontents}{egbibdata.bib}
@book{caimin2006,
title = {UML 基础和 Rose 建模教程},
address = {北京},
author = {蔡敏 and 徐慧慧 and 黄柄强},
publisher = {人民邮电出版社},
year = {2006},
month = {1}
}
\end{filecontents}
\documentclass{ctexart}
% 使用符合 GB/T 7714-2015 规范的参考文献样式
\usepackage[style=gb7714-2015]{biblatex}
% 注意加 .bib 扩展名
\addbibresource{egbibdata.bib}
\begin{document}
见文献\cite{caimin2006}。
\printbibliography
\end{document}
```
直接复制粘贴就能编译，学习 LaTeX 的体验大大增强

**Comment by stone-zeng** [comment]
我个人理解 `filecontents` 不应该作为常规使用，而只是在提交 MWE 等场合比较实用。参考文献这一类情景使用单独的文件保存比较安全，也对初学者更友好。

**Comment by muzimuzhi** [comment]
倒是可以试试，在例子里使用随发行版分发的 bib 文件（有没有中文 bib 条目）？

**Comment by sikouhjw** [comment]
> 我个人理解 `filecontents` 不应该作为常规使用，而只是在提交 MWE 等场合比较实用。参考文献这一类情景使用单独的文件保存比较安全，也对初学者更友好。
> 
> 可以考虑在其他部分增加一些有关的说明。

好的
