### ISSUE TITLE
'' 与之前汉字的间距

### ISSUE THREAD

**Issue by tanukihee** [CTeX-org/lshort-zh-cn#53]
https://github.com/CTeX-org/lshort-zh-cn/blob/550a239614e245252e2acdd22d476f30bc0ce847/src/chap/chap.02.text.tex#L166
`''` 似乎会吸收前方与汉字的间距，效果不良
![image](https://user-images.githubusercontent.com/34062491/89284890-0408ce80-d682-11ea-96d9-92807d6175c6.png)

或许可以使用
```LaTeX
双引号 `` 和\ '' 分别
```
效果图
![image](https://user-images.githubusercontent.com/34062491/89285007-361a3080-d682-11ea-9230-68c6721a655d.png)

**Comment by zepinglee** [comment]
对，所以不推荐在 CJK 的环境中使用 `''` 输入引号的方式

**Comment by stone-zeng** [comment]
Fixed in 327e68b1cecf65ed5f7b2d78d6ffd65cd9d296cc.
