### ISSUE TITLE
\hologo{TikZ} 后间距偏大

### ISSUE THREAD

**Issue by tanukihee** [CTeX-org/lshort-zh-cn#54]
https://github.com/CTeX-org/lshort-zh-cn/blob/327e68b1cecf65ed5f7b2d78d6ffd65cd9d296cc/src/lshort-zh-cn-style.sty#L168-L170
169 行结束未加 `%`，导致多出一个空格，使得 Ti*k*Z 后的间距偏大。
![image](https://user-images.githubusercontent.com/34062491/89298291-b72ff280-d697-11ea-81a4-06cf13151b90.png)

**Comment by muzimuzhi** [comment]
谢谢指出，已修复。你其实可以直接开 pull request 的。
