### ISSUE TITLE
改进建议

### ISSUE THREAD

**Issue by lihaoyu1234** [CTeX-org/lshort-zh-cn#55]
第一页中“二零二零”的“零”错误，应为“二〇二〇”。

**Comment by stone-zeng** [comment]
根据《现代汉语词典》，「零」和「〇」在此处都可以用。但文档使用的 Fandol 字体里面「〇」做得比较丑，所以用了「零」：

<img width="570" alt="Screen Shot 2020-09-03 at 16 05 47" src="https://user-images.githubusercontent.com/18233088/92088361-56fbb000-edff-11ea-8971-8c04135188e4.png">
