### ISSUE TITLE
6.4.2节有关超链接命令的描述问题

### ISSUE THREAD

**Issue by zhjscut** [CTeX-org/lshort-zh-cn#57]
![image](https://user-images.githubusercontent.com/32974196/103539418-fe364400-4ed2-11eb-9318-a4244851b010.png)
\nolinkurl 只能生成一个字符串，不能点击跳转

**Comment by zhjscut** [comment]
原文：\url 和 \nolinkurl 都生成可以点击的 URL，区别是前者有彩色，后者没有。在 \url 命 令中作为参数的 URL 里，可直接输入如 %、& 这样的特殊符号。

**Comment by muzimuzhi** [comment]
`\nolinkurl` 不产生超链接（pdf annotation）。能点击是因为部分 pdf 阅读器的功能。

**Comment by sikouhjw** [comment]
> 
> 
> `\nolinkurl` 不产生超链接（pdf annotation）。能点击是因为部分 pdf 阅读器的功能。

啊这……测试了一下 Acrobat Reader DC，确实不会跳转

**Comment by zhjscut** [comment]
> `\nolinkurl` 不产生超链接（pdf annotation）。能点击是因为部分 pdf 阅读器的功能。

原来如此，texstudio跟Mendeley都不能跳转
