### ISSUE TITLE
关于“文件的组织方式”一节的错误例子的修改建议

### ISSUE THREAD

**Issue by bro-sin** [CTeX-org/lshort-zh-cn#58]
# 问题修改建议
第一章1.6 文件的组织方式中给出的例子应当修改修改为去掉`.tex`后缀。望采纳、更新，感谢！
# 详细说明
> 下面是该问题的详细说明

在`lshort-zh-cn`的第一章的[1.6 文件的组织方式](https://github.com/CTeX-org/lshort-zh-cn/blob/master/src/chap/chap.01.basics.tex)有提到`\include`命令的用法：
> LATEX 提供了命令 \include 用来在源代码里插入文件：
> `\include{⟨filename⟩}`
> ⟨filename⟩ 为文件名，如果和要编译的主文件不在一个目录中，则要加上相对或绝对路径，例如：
> \include{chapters/a.tex} % 相对路径
> \include{/home/Bob/file.tex} % Linux/macOS 绝对路径
> \include{D:/file.tex} % Windows 绝对路径，用正斜线

而事实上，通过如下尝试：
在一个空文件夹下面建立两个文件，分别是：
```latex
%filea.tex
\documentclass{article}
\begin{document}
This is a \LaTeX \ file.
\include{fileb.tex}
%\include{fileb}
\end{document}
```
```latex
%fileb.tex
This is another \LaTeX \ file.
```
执行命令`pdflatex filea.tex`，输出的只有`filea.tex`文件的内容。
将`filea.tex`修改为：
```latex
%filea.tex
\documentclass{article}
\begin{document}
This is a \LaTeX \ file.
%\include{fileb.tex}
\include{fileb}
\end{document}
```
再执行命令`pdflatex filea.tex`，就得到了同时包含`filea.tex`和`fileb.tex`文件内容的输出结果。

可以发现，在使用相对路径时，不应当使用` \include{chapters/a.tex} `这种形式的命令，而应当改为` \include{chapters/a}`这种形式，否则编译不出`a.tex`文件中的内容。

同时，在查阅了`lshort`原文后，注意到，在Chapter 1的[1.8 Big Projects](https://github.com/oetiker/lshort/blob/master/book/src/things.tex)中是这么介绍的：
> When working on big documents, you might want to split the input file into several parts. LATEX has two commands that help you to do that.
> `\include{filename}`
> Use this command in the document body to insert the contents of another file named filename.tex.  Note that LATEX will start a new page before processing the material input from filename.tex. 

可以看出，虽然原文没有给出使用示例，但是确实是指的是使用`\include{chapters/a}`这种形式的命令。
# 相关问题
出于对上述错误的思考，我又尝试了另外一种，就是使用绝对路径，但结果令人惊讶，无论我是否带后缀，`\include`命令都无法编译出来；而使用`\input`命令，无论我是否带后缀，都能编译出理想的效果。
# 参考链接
1. 我本来遇到的问题是这个：https://wenda.latexstudio.net/q-5285.html
2. lshort原文对应章节文档：https://github.com/oetiker/lshort/blob/master/book/src/things.tex

**Comment by stone-zeng** [comment]
在 LaTeX 2020-10-01 中，`\include` 和 `\includeonly` 会去除文件名结尾的 `.tex`（同时也能正确处理文件名中包含空格的情况），但在 ltnews 中并没有指出这一点（空格是说了的）。

具体代码：

https://github.com/latex3/latex2e/blob/572e060e935419c1ffc9edbbcca2914f6fd0cd13/base/ltfiles.dtx#L708-L719
