### ISSUE TITLE
如何在src目录下编译

### ISSUE THREAD

**Issue by Haaaarry** [CTeX-org/lshort-zh-cn#62]
如题，能否给个安装教程谢谢

**Comment by sikouhjw** [comment]
https://github.com/CTeX-org/lshort-zh-cn#manually-typesetting

**Comment by Haaaarry** [comment]
> https://github.com/CTeX-org/lshort-zh-cn#manually-typesetting
这个我看了，但是不知道“在目录下编译”的含义，我不知道在哪里把那段英文放进去。

**Comment by sikouhjw** [comment]
> 
> 
> > https://github.com/CTeX-org/lshort-zh-cn#manually-typesetting
> > 这个我看了，但是不知道“在目录下编译”的含义，我不知道在哪里把那段英文放进去。

命令行编译，去看 `install-latex-guide-zh-cn`

**Comment by Haaaarry** [comment]
> > > https://github.com/CTeX-org/lshort-zh-cn#manually-typesetting
> > > 这个我看了，但是不知道“在目录下编译”的含义，我不知道在哪里把那段英文放进去。
> 
> 命令行编译，去看 `install-latex-guide-zh-cn`

已经解决问题了！非常感谢
