### ISSUE TITLE
建议在表6.1中添加 gbt7714 的排版效果

### ISSUE THREAD

**Issue by OsbertWang** [CTeX-org/lshort-zh-cn#65]
如题。
提出这个建议有三个原因：
一、被很多国内高校的学位论文样式要求搞烦了，国内很多高校虽然在学位论文样式要求中提到了这个国标，但给出的示例往往和国标不一致。不如在表6.1中给出来排版效果，也方便日后说明。
二、6.1.6 节有对 gb7714-2015 的介绍。
三、经常被询问中文的参考文献该如何用bibtex。

**Comment by zepinglee** [comment]
OK，我加一下。
