### ISSUE TITLE
应该更早说明命令 `\mathbb` 的来源

### ISSUE THREAD

**Issue by syvshc** [CTeX-org/lshort-zh-cn#66]
在 4.2 节的结尾有例
![image](https://user-images.githubusercontent.com/38098591/117397425-b3831200-af2e-11eb-98b3-8a2cfbc8517e.png)
4.3.6 节也有两次提到 `\mathbb`
![image](https://user-images.githubusercontent.com/38098591/117397480-d7deee80-af2e-11eb-9159-1857ec2d5db3.png)
均未提及这个命令的来源, 
而在 4.7 节才提到某些字体命令需要宏包的支持
![image](https://user-images.githubusercontent.com/38098591/117397561-fe9d2500-af2e-11eb-803a-b0fb0c2b8dab.png)
行文顺序可能有一些问题.

**Comment by stone-zeng** [comment]
这里给出的很多公式仅作为示例，细究起来像 `^`、`_` 这样的东西也是在给出解释之前就用了，个人认为并不是很妨碍理解。但使用 `\mathbb` 的地方确实应该说明一下要调 `amssymb`。

**Comment by syvshc** [comment]
嗯是的,&nbsp;我的意思是要么给示例的时候提一下 `amssymb`,&nbsp;要么更换示例,&nbsp;不然读者复制代码使用的时候会报错.&nbsp;至于 `^`, `-`&nbsp;直接使用不会有问题.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xiangdong ***@***.***&gt;; 
发送时间: 2021年5月7日(星期五) 中午1:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CTeX-org/lshort-zh-cn] 应该更早说明命令 `\mathbb` 的来源 (#66)





 
这里给出的很多公式仅作为示例，细究起来像 ^、_ 这样的东西也是在给出解释之前就用了，个人认为并不是很妨碍理解。但使用 \mathbb 的地方确实应该说明一下要调 amssymb。

**Comment by syvshc** [comment]
嗯是的, 我的意思是要么给示例的时候提一下 `amssymb`, 要么更换示例, 不然读者复制代码使用的时候会报错. 至于 `^`, `-` 直接使用不会有问题. （为什么通过邮件回复的时候会有 `&nbsp` 这种东西...
