### ISSUE TITLE
添加 l3 相关内容

### ISSUE THREAD

**Issue by tanukihee** [CTeX-org/lshort-zh-cn#68]
随着 l3 的使用越来越广泛，要不要在 lshort 中补充 l3 相关的内容？

大概只需要讲 expl3 与 xparse 的基础部分？

**Comment by muzimuzhi** [comment]
`lshort-zh-cn` 偏入门，我支持介绍一些文档 `texdoc xparse` 里的用户命令，但反对介绍文档 `texdoc interface3` 里的主要面向开发者的内容。

与 `texdoc interface3` 对应的，是 tex 里的 `\def`, `\expandafter`, `\dimexpr`, latex2e 里的 `\@gobble`, `\@ifnextchar`, `\IfFileExists` 等内容。如果要介绍，似乎都得介绍。而且介绍 `expl3` 的部分内容，需要铺垫 tex 的基础（如展开控制、catcode），似乎超出了 `lshort-zh-cn` 的任务。

**Comment by muzimuzhi** [comment]
感谢

**Comment by syvshc** [comment]
建议在参考文献中加入`texdoc source2e`, `texdoc interface3`/`texdoc source3` 以及 `texdoc expl3`

**Comment by muzimuzhi** [comment]
发现目前 lshort-zh-cn 的参考文献部分，像是（狭义的）参考文献和相关阅读的混合体，不够好。

**Comment by muzimuzhi** [comment]
`xparse` 已经并入 latex kernel，可以简要介绍，记录在 #101。

`expl3` 对面向入门用户的 lshort-zh-cn 而言，太高深了。如果有一个面向开发者的入门文档，肯定要介绍 `expl3`/`interface3`。
