### ISSUE TITLE
希望添加一些 BibLaTeX 的内容

### ISSUE THREAD

**Issue by OsbertWang** [CTeX-org/lshort-zh-cn#7]
现在 BibLaTeX 的应用越来越广泛，不知道这部分内容什么时间能够添加到 lshort-zh 中？

**Comment by louisstuart96** [comment]
没写的原因之一是我自己用得少，怕写错了误导别人……如果你对 `biblatex` 经验比较足的话，可以拟个稿子推个 PR 过来。

**Comment by hushidong** [comment]
看到啸行和zeeping在qq群里的提议了，biblatex我的确用的多点，我先写一个初稿，抛砖引玉，然后大家不断完善。

**Comment by OsbertWang** [comment]
谢谢胡老师

**Comment by louisstuart96** [comment]
@hushidong 我正在改，行文上尽可能和 lshort 的其它部分一致。

我的想法是，作为 lshort 这种文档，尽可能地不加复杂的功能，把最简单的用法告诉用户就可以了，复杂的部分最好鼓励用户自己查文档。
