### ISSUE TITLE
建议修改3.6.6行距控制的文字描述内容

### ISSUE THREAD

**Issue by Quietplant** [CTeX-org/lshort-zh-cn#70]
![image](https://user-images.githubusercontent.com/12099877/121807615-7de8eb80-cc87-11eb-8cc7-ef111d69685f.png)
加粗部分“表格的首个单元格不能直接使用中括号[]”表述容易引起误解，建议修改为“表格第二行之后的首个单元格不能直接以中括号[]开始”……

**Comment by muzimuzhi** [comment]
感谢你的反馈，已修改。
