### ISSUE TITLE
When it comes to writing the year per digit in Chinese characters, 0 is supposed to be written as "〇" (instead of "零").

### ISSUE THREAD

**Issue by septsea** [CTeX-org/lshort-zh-cn#76]
The cover of the latest `lshort-zh-cn` writes the year of 2021 as `二零二一年`.

However, according to *General rules for writing numerals in public texts* (GB/T 15835-2011, a voluntary national standard of the People's Republic of China), "the Chinese character for `0` when used for numbering is `〇`" (see 5.2.5; the definition for *numbering* is in 3.3).

Hence, I suggest fixing it.

**Comment by stone-zeng** [comment]
I use `零` to avoid the bad design of `〇` in the default font Fandol Song.

**Comment by muzimuzhi** [comment]
similar to #55

**Comment by septsea** [comment]
Dear @stone-zeng and @muzimuzhi,

Thank you for your replies!

I acknowledged the poor design of `〇`.

As the letter "T" (tuījiàn) suggests, GB/T 15835-2011 is merely a voluntary standard. However, I suggest that the reason for which "零" has to be used be put somewhere as a notice. Moreover, I do not think it is something unresolvable.

Septsea

**Comment by muzimuzhi** [comment]
- 《GB/T 15835—2011 出版物上数字用法》为推荐标准，约束范围为
    > 各类出版物（文艺类出版物和重拍古籍除外）。政府和企事业单位公文，以及教育、媒体和公共服务领域的数字用法，也可参照本标准执行。
 - `lshort-zh-cn.pdf` 算不算出版物，我表示怀疑
 - 即使是标准的出版物，也有在年份中使用「零」的，例如《新华每日电讯》2022年01月06日，第7版文章[《书写促进人类进步新篇章》](http://mrdx.cn/content/20220106/Page07DK.htm)，副标题《二零二二年中国外交令人期待》。

我觉得不必纠结。

**Comment by septsea** [comment]
Yeah, the standard is only **voluntary**; following the rule is preferable, though. I just **suggested** fixing "the bug"; `零` is not **wrong**.
