### ISSUE TITLE
关于手册4.6 节公式中的间距的修改建议

### ISSUE THREAD

**Issue by SwitWu** [CTeX-org/lshort-zh-cn#77]
4.6 节说命令 `\:`、`\;` 和 `\!` 只用于数学环境，但我在文档 [latex2e: An unofficial reference manual](https://texdoc.org/serve/latex2e.pdf/0) 中看到：只要加载了 `amsmath` 宏包或者使用的是 `2020-10-01` 及之后的 LaTeX 版本，这些命令既能用于文本模式，也能用于数学模式，所以 lshort 是否需要将相关介绍进行更改？另外建议给出这些长度命令的具体长度值，方便读者建立准确的认识。

**Comment by stone-zeng** [comment]
长度命令的具体长度值在文本和数学模式下有细微差别，完整描述比较复杂，所以不准备在文档中介绍。

**Comment by SwitWu** [comment]
那第一个问题呢？

**Comment by stone-zeng** [comment]
已经改过了～
