### ISSUE TITLE
索引中 "\flushbottom" 被归入错误的部分

### ISSUE THREAD

**Issue by Ming-Hua** [CTeX-org/lshort-zh-cn#78]
在目前最新的6.04版中，"\flushbottom"这个命令并没有归入索引中F字母部分，而是自成一个空格部分（在符号部分和字母A部分之间，121页）。

原因是文件chap.05.style.tex中第606行``\cmdindex{raggedbottom, flushbottom}``在逗号后多了一个空格，这个空格就被索引生成程序当成是\flushbottom命令的一部分了。

**Comment by stone-zeng** [comment]
感谢反馈～

**Comment by muzimuzhi** [comment]
或者在 `\@for\@ltxcmd:=#1\do{...}` 里把 `\@ltxcmd` 两头的空格去了
https://github.com/CTeX-org/lshort-zh-cn/blob/508462817d26387e5a11efab5f4d1e22cf563eff/src/lshort-zh-cn-style.sty#L219-L229
