### ISSUE TITLE
Errors when using make.bat to compile

### ISSUE THREAD

**Issue by houhuawei23** [CTeX-org/lshort-zh-cn#82]
Hardware:
Laptop:    DELL G15 5511
CPU:    11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz   2.30 GHz

OS:
Window11

** When I use the cmd shell to run the make.bat,  it reports some errors that I cant solve.**

> PS C:\Users\hhw\Desktop\z临时\lshort-zh-cn-6.03\src> .\make.bat
'xelatex' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'makeindex' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'xelatex' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'xelatex' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

![make bat](https://user-images.githubusercontent.com/36103474/186588406-feda22d2-8316-4b6d-adca-97cb6ce33327.png)

How can I solve it?

**Comment by syvshc** [comment]
@houhuawei23 是否正确安装了 LaTeX 发行版且添加了环境变量 texlive/20xx/bin/win32

**Comment by houhuawei23** [comment]
> @houhuawei23 是否正确安装了 LaTeX 发行版且添加了环境变量 texlive/20xx/bin/win32

没有，TeX Live和MikTex都可以吗

**Comment by houhuawei23** [comment]
> @houhuawei23 是否正确安装了 LaTeX 发行版且添加了环境变量 texlive/20xx/bin/win32

没有，TeX Live和MikTex都可以吗

**Comment by AlphaZTX** [comment]
@houhuawei23 如果环境变量已确保正常添加的话，无论哪种发行版都可以正常使用。

**Comment by AlphaZTX** [comment]
@houhuawei23 如果环境变量已确保正常添加的话，无论哪种发行版都可以正常使用。

**Comment by syvshc** [comment]
@houhuawei23 都可以，发行版后注意添加环境变量并在命令行运行 tex -v 来测试是否安装成功

**Comment by houhuawei23** [comment]
感谢 ！！@syvshc @AlphaZTX
