### ISSUE TITLE
几处小的优化建议

### ISSUE THREAD

**Issue by amcruvtij** [CTeX-org/lshort-zh-cn#84]
- P51下方 4.8.2第一行 「粗体标签，斜体正文」与后文「**标签，**内容」不统一 可将「正文」改为「内容」

- P56 表4.8巨算符 \oiint也是常用符号 但不在amsmath宏包中 似乎在unicode-math与esint宏包中 希望能列入表中 

- P73中下 5.5.2 代码段前一行「 \ 命令的用法详见 8.1.1 节」中「 \ 」可能应为「 \renewcommand 」 

- P84倒数第二行 6.4.1 两处「 \<option2\>={value} 」可能应为「 \<option2\>=\<value\> 」 

- P90下方 7.2.2 列表第一项中「draw和fill分别指定填充和描边的颜色」 应「draw与fill对换」或「填充 与 描边 对换」 

- P92 7.2.3最后一行 「节点」改为「结点」与上下文一致 

- P93 本页第三个列表项（7.2.3第五个） 「 node font=\<font command\> 」可能应为「 node font={\<font command\>} 」 

- P108 B.2 本页倒数第四个列表项中「如果错误提示里的文件名带 .cls 或者 .sty 扩展名，那么很显然，是因为没有安装所需的宏包或文档类。」应「.cls与.sty对换」或「宏包 与 文档类 对换」

**Comment by stone-zeng** [comment]
> P56 表4.8巨算符 \oiint也是常用符号 但不在amsmath宏包中 似乎在unicode-math与esint宏包中 希望能列入表中

整个第四章基本是以 `amsmath` 为主的，`unicode-math` 则在 5.1 节修改字体的地方提了一下，所以这个暂时不打算列进来。

**Comment by muzimuzhi** [comment]
FYI, closed by https://github.com/CTeX-org/lshort-zh-cn/commit/7ef3d6e784b533160c6316c36f464f288de77474.
