### ISSUE TITLE
请教还有基于tex排版精美的中文书籍或手稿呢？

### ISSUE THREAD

**Issue by nceeliev** [CTeX-org/lshort-zh-cn#88]

**Comment by latexstudio** [comment]
美不美没有什么标准的，更多是各种版式堆积起来，有些制作还是蛮用心的，可以到这里看看：https://www.latexstudio.net/index/lists/index/type/21/cate/22.html 可以找见的模板。

**Comment by AlphaZTX** [comment]
与 lshort-zh-cn 无关的问题请到 [CTeX-org/forum](https://github.com/CTeX-org/forum) 提问。
