### ISSUE TITLE
此处的文字排版并不一致，是bug或者有意为之？

### ISSUE THREAD

**Issue by AzureRubia-Guet** [CTeX-org/lshort-zh-cn#93]
两页之间并没有对齐
<img width="1203" alt="issue" src="https://github.com/CTeX-org/lshort-zh-cn/assets/97378825/0b2def22-05de-4c06-98b1-d9cae5a15b39">

**Comment by AzureRubia-Guet** [comment]
初学者，在看了源码之后没有发现异常，是一串连续的item。并没有能力改代码提交pr，只能提交issue问一下了

**Comment by syvshc** [comment]
这是 book 文档类默认的 twoside 样式, 可以区分左右页的样式, 比如装订的时候保证两侧的间距一致

**Comment by stone-zeng** [comment]
可以打开双页视图看一下效果：

<img width="380" alt="Screenshot 2024-06-07 at 22 24 27" src="https://github.com/CTeX-org/lshort-zh-cn/assets/18233088/c09deeb6-44f4-4890-939d-77ba6ecd1042">
