### ISSUE TITLE
表 4.2: 数学字母字体

### ISSUE THREAD

**Issue by mengchaoheng** [CTeX-org/lshort-zh-cn#94]
```
$\CMcal{ABCDE}$                  & \cmd{mathcal}\marg*{\ldots}   & 仅提供大写字母 \\
```
这一行的CMcal需要mathrsfs包依赖，若使用
```
\usepackage{unicode-math}
\setmathfont{XITS Math}
```
则编译的字符和普通文本一样

**Comment by AlphaZTX** [comment]
首先建议规范提问。

> 这一行的CMcal需要mathrsfs包依赖，……

你说的是哪个文件的哪一行？虽然看到 issue 的人不难把这一行 `grep` 出来，但还是请注明是在第几行。建议改为：

> `chap.04.math.tex` 第 690 行的 `\CMcal` 命令需要 mathrsfs 包依赖，……

我将在本 issue 的下一条回复中回答你的问题。

**Comment by mengchaoheng** [comment]
谢谢指正。我在参考本书时看到这里没有指出所依赖的包遂提一下。至于使用unicode-math包设置XITS math字体，造成的冲突，也许超出了本项目的范围。

**Comment by AlphaZTX** [comment]
首先，`\CMcal` 不是 mathrsfs 包提供的命令，而是 euscript 包提供的。`chap.04.math.tex` 第 690 行的 `\EuScript` 也是 euscript 包提供的。

加载 euscript 包后，`\CMcal` 等同于不加载 euscript 时的 `\mathcal`。在默认设置下，`\mathcal` 的效果是将数学模式下的字体切换到 `cmsyN` 这样的 OMS 字体编码的字体（`N` 等于几取决于你的字号；另，如果你不知道字体编码是什么，可以去看 `encguide`、`fntguide`、[我的幻灯片](https://github.com/AlphaZTX/enctalk-cn)等资料）。当然，对于下面的例子：

```latex
\documentclass{article}
\begin{document}
$\mathcal{A}$
\end{document}
```

`\mathcal` 调用的字体一定是 `cmsy10`。无论是 `cmsy` 多少，这些字体都属于 Computer Modern family。看起来大致是这样：

<img width="400" src="https://github.com/user-attachments/assets/41d24250-00b3-4d27-bebe-1eb6d9b98248" />

加载 euscript 包只是让你多了一种 `\mathcal` 字体的选择。这套字体是 Hermann Zapf 画的，长这样：

<img width="360" src="https://github.com/user-attachments/assets/35e7112c-f6e5-4fb3-b29d-bf1e64e5ba3d" />

在 euscript 的代码中，`\CMcal` 是这样定义的：

```tex
\let\CMcal=\mathcal
```

`\CMcal` 直接被定义为 `\mathcal` 了。

加载 unicode-math 并设置了不同于 `latinmodern-math.otf` 的数学字体后，所有数学模式下的 NFSS 字体命令（如果你不知道 NFSS 是啥，请移步 `fntguide` 等文档）都将对应于你设置的数学字体，而不是 `cmsyN`。所以……我写到这儿才知道你说的“则编译的字符和普通文本一样”中的“普通文本”是啥意思，这根本不是所谓的“普通文本”好吗？建议这样表述：

> 则 `$\CMcal{ABCDE}$` 得到的不是 cm 字体，而是 XITS Math。

或者，退一步，假设你不会像上面一样表述，你也可以配图：

> 则 `$\CMcal{ABCDE}$` 得到的效果和 `$\mathcal{ABCDE}$` 得到的结果一样（如图）：
> [图片]

接上面的“所以”。所以，`\CMcal` 切换的字体，在你给出的例子下，是 XITS Math。XITS Math 中的数学手写体字母部分如下：

<img width="800" src="https://github.com/user-attachments/assets/63dccfc5-18ce-46b3-9c39-a6f0046e4cc4" />

你把默认的数学字体改为 XITS Math，默认的 `\mathcal` 也要改为 XITS Math。这本来就是一个正常的现象，不在预期外。

**最后，不建议修改 lshort-zh-cn 的字体设置。如果你已经创建了修改过字体设置的 branch，不要试图把修改字体设置的更新提交到 main branch，lshort-zh-cn 的维护者不会、也不应当 merge 类似的更新。**

**Comment by muzimuzhi** [comment]
> ```
> $\CMcal{ABCDE}$                  & \cmd{mathcal}\marg*{\ldots}   & 仅提供大写字母 \\
> ```
>
> 这一行的CMcal需要mathrsfs包依赖

<img width="505" alt="image" src="https://github.com/user-attachments/assets/7f7990f8-ee73-4726-8820-078487d67718" />

如果只看 PDF，这里表达的就是使用 `\mathcal` 能得到左侧的书法风格的大写字母，无需加载宏包。这个表述是正确的，无需修改。

源文件里用了 `\CMcal` 的原因上面已经介绍了。

https://github.com/CTeX-org/lshort-zh-cn/blob/e95288a697822a6f63e6f2eb1b9160a6f324c566/src/chap/chap.04.math.tex#L690-L692

源文件会比 PDF 包含更多信息，但它们未必都对 PDF 的读者有用。

> 我在参考本书时看到这里没有指出所依赖的包遂提一下。

也许需要完整的具体例子。（请总是提供足够的信息，足够到能让他人方便地复现问题。）

以下假设 `unicode-math` + `XITS Math`。

`lshort-zh-cn` 里的表4.2: 数学字母字体，主要面向没使用 `unicode-math` 设置数学字体的情况。`unicode-math` 改变了很多东西。[^1][^2]@AlphaZTX 的评论 https://github.com/CTeX-org/lshort-zh-cn/issues/94#issuecomment-2551396353 末尾，截图展示了「XITS Math 中的数学手写体字母部分」，但是，默认设置下 `\mathcal` 和 `\mathscr` 都得不到他评论截图里的手写体字母。[^3]

`unicode-math` 文档 (v0.8r, 2023/08/13) 5.4.3 "Calligraphic vs. Script variants" 讨论了这个情况，并提供了解决方案（需要数学字体支持）：
```tex
\usepackage{unicode-math}
\setmathfont{XITS Math}
\setmathfont{XITS Math}[range={cal, bfcal}, StylisticSet=1]
```
![image](https://github.com/user-attachments/assets/ae08c345-8ea9-4fce-83a3-b575d62c29ec)

<details><summary>截图对应例子</summary>
<p>

```tex
% !TeX program = xelatex
\documentclass{article}
\usepackage{unicode-math}
\setmathfont{XITS Math}

\def\setss{\setmathfont{XITS Math}[range={cal, bfcal}, StylisticSet=1]}

\begin{document}
\begin{tabular}{lllll}
         & \verb|\mathcal|         & \verb|\mathbfcal|
         & \verb|\mathscr|         & \verb|\mathbfscr|   \\
  before & $\mathcal{ABCDE}$       & $\mathbfcal{ABCDE}$ 
         & $\mathscr{ABCDE}$       & $\mathbfscr{ABCDE}$ \\
  after  & \setss$\mathcal{ABCDE}$ & $\mathbfcal{ABCDE}$
         & $\mathscr{ABCDE}$       & $\mathbfscr{ABCDE}$
\end{tabular}
\end{document}
```

在实际文档中，第二个 `\setmathfont` 不用延后到在 document 里使用。

</p>
</details> 

[^1]: 比如，如果字体提供了，手写字体也可以有小写字母、可以有粗体，详见 `texdoc unimath-symbols` (v0.8r, 2023/08/13), sec. 13.1.8 "Script, Latin, lowercase" 和 sec. 13.2.9 "Bold script, Latin, uppercase"。
[^2]: `unicode-math` 实际推荐使用以 `sym` 开头的数学字母字体命令，如 `\symcal`, `\symscr`，而 `\mathcal` 这种仅作为兼容性支持。不过没有得到广泛实践。
[^3]: 因为 Unicode 只给 calligraphic 和 script 分配了一份码位，所以即使字体提供了两套 glyph，也只有通过 stylistic set 才能用上。

**Comment by AlphaZTX** [comment]
@muzimuzhi [外部链接 (知乎)](https://zhuanlan.zhihu.com/p/569922028) 评论区值得关注一下。目前的数学字体都把 script 风格切换的功能放到 `lookup ss01` 里了，但 UTC 更推荐用 SVS 序列实现，以后可能也需要关心 `cmap` 表。

**Comment by mengchaoheng** [comment]
学习到了很多，谢谢你们。主要是平时没规范提问的习惯，加上知识有限，形成不了太深刻的阐述。

我简单描述一下我的工作，我在维护[华南理工大学硕/博士学位论文LaTeX模板](https://github.com/mengchaoheng/SCUT_thesis)模板时，需要将数学公式的字体改为使用`Times New Roman`，以前的字体和本项目这本书所呈现的一样。我希望修改字体后，数学符号可以像lshort所展示的那样，虽然字体变了，但我想尽力使他依然呈现类似的效果（我不知道我的想法是否正确）。

1.我新建一个test1.tex文件进行测试:
```
\documentclass{article}
\usepackage{xcolor}  
\usepackage{enumitem}  
\usepackage[no-math]{fontspec}        
\usepackage{xeCJK}            
\usepackage{booktabs}   
\usepackage{amsmath}   
\usepackage{latexsym}  
\usepackage{yhmath}    
\usepackage{amssymb}  
\usepackage{eucal}   % \EuScript
\usepackage{mathrsfs}    
% 设置正文字体
\setmainfont{Times New Roman} % 正文数字和字母使用 Times New Roman
% 设置中文正文字体为 SimSun
\setCJKmainfont{SimSun}       % 正文中文使用 SimSun
%%下面的定义是lshort书中符号表所需要的定义%%%
\newenvironment{symbols}[1]%
  {\small\def\arraystretch{1.5
  }
  \begin{tabular}{@{}#1@{}}}%
  {\end{tabular}}
%%%%%%%%%%%%%%%%%%%%%%%%
\begin{document}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
这是正文部分，中文使用 SimSun 字体，英文使用 Times New Roman 字体。

下表为lshort中文版中，表 4.2: 数学字母字体的内容，新增了一行测试mathcal命令。

\begin{table}[htp]
  \centering
  \caption{数学字母字体} \label{tbl:math-fonts}
  \begin{tabular}{*{3}{l}}
  \hline
  \textbf{示例}    & \textbf{命令} & \textbf{依赖的宏包}\\
  \hline
  $\mathnormal{ABCDE abcde 1234}$  & {mathnormal}\{\ldots\}&       \\
  $\mathrm{ABCDE abcde 1234}$      & {mathrm}\{\ldots\}    &       \\
  $\mathit{ABCDE abcde 1234}$      & {mathit}\{\ldots\}    &       \\
  $\mathbf{ABCDE abcde 1234}$      & {mathbf}\{\ldots\}    &       \\
  $\mathsf{ABCDE abcde 1234}$      & {mathsf}\{\ldots\}    &       \\
  $\mathtt{ABCDE abcde 1234}$      & {mathtt}\{\ldots\}    &       \\
  $\mathcal{ABCDE}$                  & {mathcal}\{\ldots\}   &     \\ 
  $\CMcal{ABCDE}$                  & {CMcal}\{\ldots\}   & 仅提供大写字母 \\
  \hline
  $\EuScript{ABCDE}$               & {mathcal}\{\ldots\}   & {eucal} 仅提供大写字母 \\
  $\mathscr{ABCDE}$                & {mathscr}\{\ldots\}   & {mathrsfs} 仅提供大写字母\\
  $\mathfrak{ABCDE abcde 1234}$    & {mathfrak}\{\ldots\}  & {amssymb} 或 {eufrak}  \\
  $\mathbb{ABCDE}$                 & {mathbb}\{\ldots\}    & {amssymb} 仅提供大写字母 \\
  \hline
  \end{tabular}
\end{table}
\end{document}

```
结果是如下：
![截屏2024-12-18 23 20 34](https://github.com/user-attachments/assets/820c8c73-b6d8-4052-bf30-676078eddb43)

>加载 euscript 包后，\CMcal 等同于不加载 euscript 时的 \mathcal。

注释掉\usepackage{eucal}和表格中CMcal、EuScript命令，通过简单的对比确实如此。

2.我注意到英文版的lshort是如下表（抱歉没找到代码，贴图用作参考）：
![截屏2024-12-18 23 21 39](https://github.com/user-attachments/assets/b825ef80-3948-4a1f-a3e2-f3ed3657dd9f)

3.我简单更改test1.tex文件得到test2.tex
```
\documentclass{article}
\usepackage{xcolor}  
\usepackage{enumitem}  
\usepackage[no-math]{fontspec}        
\usepackage{xeCJK}            
\usepackage{booktabs}   
\usepackage{amsmath}   
\usepackage{latexsym}  
\usepackage{yhmath}    
\usepackage{amssymb}   
\usepackage{eucal}   % \EuScript
\usepackage{unicode-math} 
\setmathfont{XITS Math} 
% 设置正文字体
\setmainfont{Times New Roman} % 正文数字和字母使用 Times New Roman
% 设置中文正文字体为 SimSun
\setCJKmainfont{SimSun}       % 正文中文使用 SimSun
%%%%%%%%%%%%下面的定义是lshort书中符号表所需要的定义%%%%%%%%%%%

\newenvironment{symbols}[1]%
  {\small\def\arraystretch{1.5
  }
  \begin{tabular}{@{}#1@{}}}%
  {\end{tabular}}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{document}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
这是正文部分，中文使用 SimSun 字体，英文使用 Times New Roman 字体。

利用unicode-math包，将表 4.2的命令改为：
\begin{table}[htp]
  \centering
  \caption{数学字母字体} \label{tbl:math-fonts}
  \begin{tabular}{*{3}{l}}
  \hline
  \textbf{示例}    & \textbf{命令} & \textbf{依赖的宏包}\\
  \hline
  $\symnormal{ABCDE abcde 1234}$  & {symnormal}\{\ldots\}&       \\
  $\symrm{ABCDE abcde 1234}$      & {symrm}\{\ldots\}    &       \\
  $\symit{ABCDE abcde 1234}$      & {symit}\{\ldots\}    &       \\
  $\symbf{ABCDE abcde 1234}$      & {symbf}\{\ldots\}    &       \\
  $\symsf{ABCDE abcde 1234}$      & {symsf}\{\ldots\}    &       \\
  $\symtt{ABCDE abcde 1234}$      & {symtt}\{\ldots\}    &       \\
  $\symcal{ABCDE}$                  & {symcal}\{\ldots\}   &   \\
  $\CMcal{ABCDE}$                  & {CMcal}\{\ldots\}   & 仅提供大写字母 \\
 \hline
  $\EuScript{ABCDE}$               & {mathcal}\{\ldots\}   & {eucal} 仅提供大写字母 \\
  $\symscr{ABCDE}$                & {symscr}\{\ldots\}   & \\
  $\symfrak{ABCDE abcde 1234}$    & {symfrak}\{\ldots\}  &   \\
  $\symbb{ABCDE}$                 & {symbb}\{\ldots\}    &    \\
  \hline
  \end{tabular}
\end{table}
\end{document}
```
结果如下：
![截屏2024-12-18 23 46 20](https://github.com/user-attachments/assets/c0b459eb-dc4b-4e0e-ba6c-fa3b7c9129f4)


问题：我不知道这个效果是否正确反应了XITS Math字体集的内容，或者有没有办法使得我在使用unicode-math包设置XITS Math字体时依然呈现和lshort原文一样的效果？

我已经基于test2.tex实现了lshort中文版第4.9节 符号表的内容，除个别符号不支持外，绝大多数符号都按照预期呈现了。

**Comment by mengchaoheng** [comment]
> unicode-math 文档 (v0.8r, 2023/08/13) 5.4.3 "Calligraphic vs. Script variants" 讨论了这个情况，并提供了解决方案（需要数学字体支持）：

才看到，确实解决了symcal，完美复现了。打扰了，谢谢大家！

**Comment by muzimuzhi** [comment]
> [外部链接 (知乎)](https://zhuanlan.zhihu.com/p/569922028) 评论区值得关注一下。

@AlphaZTX 从 LaTeX 使用角度，知乎文章末尾的例子里，`range=cal` 改为和 `unicode-math` 文档里用的 `range={cal,bfcal}`，对 SITX 和 XTIS 字体更好。

我也向 https://github.com/CTeX-org/lshort-zh-cn/issues/94#issuecomment-2551491720 里的例子和截图增加了 `\mathbfcal` 和 `\mathbfscr` 的输出。
