### ISSUE TITLE
关于对表格内容部分的疑问

### ISSUE THREAD

**Issue by Mikachu2333** [CTeX-org/lshort-zh-cn#95]
您好！lshort是我的入门指南，它在我学习使用latex的过程中帮了我很多。

但是，在鄙人尝试进行复杂表格排版的过程中（同时含有列宽、行高、且成比例、类三线表样式、横向与纵向合并单元格、表注、表头、跨页等特性），发现如果仅按照正文部分介绍的办法进行操作，不仅会导致引入较多宏包，还会较严重地影响表格在编辑状态下的显示与格式化，难以使初学者快速弄懂明白单元格的对应（对齐）关系。

而tabularry宏包能较好地解决该问题（也确实在附录中提及了此包），所以想问一下为什么不直接在正文中直接提及此包。例如，在第27页表格小节的第一段结尾加上一句 `本节仅叙述了基本的表格排版方法，如需排版复杂表格敬请参照附录B3.3` 呢？

这样可以较好的引导用户自行参考附录内容（我当时就没发现附录这么有用，结果绕了很多弯路，所以如果在正文中提一句，略进行一些引导或许会更好）

此外，另想问一下附录里面宏包的排序依据是什么，因为找了半天没看明白是按何种方式进行排序的（总不能是推荐程度吧）

**Comment by stone-zeng** [comment]
`tabularray` 比较新（2021 年才发布），很多教程可能都没有包含，所以没放在正文介绍。之后可以考虑在正文中也提及一下。（就好比 C++ 现在虽然有 `std::print` 但你去找教程很多还都是只讲 `std::cout` 甚至 `printf` 的）

> 此外，另想问一下附录里面宏包的排序依据是什么，因为找了半天没看明白是按何种方式进行排序的（总不能是推荐程度吧）

没什么顺序，我们是乱写的（

**Comment by Mikachu2333** [comment]
> 很多教程可能都没有包含

虽然网上确实没两个用tabularray的示例，但是tabularray自己的那个中文文档就基本够用了

> 没什么顺序，我们是乱写的（

原来是这样的吗，太离谱了（

感觉可以整个按推荐顺序排序之类的东西，或者干脆按字母顺序排，加一句 `本表不代表推荐顺序排序`

**Comment by AlphaZTX** [comment]
> 没什么顺序，我们是乱写的（

其实不然。看起来确实没啥顺序，但这里试图按照常用度排序，只是所谓“常用度”没有一个可靠的指标。因此，这个 issue 不考虑按照 @Mikachu2333 的方法解决。
