### ISSUE TITLE
关于空白页的疑惑

### ISSUE THREAD

**Issue by Mikachu2333** [CTeX-org/lshort-zh-cn#97]
## 问题
为什么第10页没有任何内容？我检查了chapter1和chapter2，但是没有发现额外的`\newpage`等命令，因能力不足无法进一步排查。

## 可能相关的内容
1. LaTeX WorkShop提示第一章存在 `Underfull \\hbox (badness 10000)`
2. 我注释了所有内容仅保留了第一章，我认为是第一章导致的问题
3. 我注意到了 Chapter1 中 `Line 421`的那个浮动表格，并且极度怀疑是由其导致的换页异常（因为曾遇到过相似的问题），但我不知道如何在不更换其他环境的情况下修复它（此前我是通过使用`tabularray`包的`longtblr`修复的此问题）

**Comment by Mikachu2333** [comment]
更新，我注意到6.01是最后一个正常的版本 https://github.com/CTeX-org/lshort-zh-cn/releases/tag/v6.01

**Comment by Mikachu2333** [comment]
悲，刚刚发现，这似乎是有意为之的……看起来是每个chapter都以书籍的样式显示，从右侧的那一页开始……

唯一的缺点大概就是在手机怎么看怎么怪了……

我还以为是缺页了……

**Comment by AlphaZTX** [comment]
book 文档类里面有一行 `\ExecuteOptions{letterpaper,10pt,twoside,onecolumn,final,openright}`，可以解答你的问题。

**有热情为社区作出贡献是好事，但我认为你可能需要仔细阅读一遍 `lshort-zh-cn`，然后再酌情提 issue 或者 pr。**
